config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  get '/' => 'posts#index'

  get '/users' => 'users#login'
  get '/users/list' => 'users#list'

  get '/users/login' => 'users#login', as: 'login_user'
  get '/users/clear' => 'users#clear'
  post '/users/login' => 'sessions#create'
  post '/users/:id/change_role' => 'users#change_role'

  get '/posts' => 'posts#index'
  get '/posts/:id' => 'posts#show', as: 'post'

  get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  patch '/posts/:id' => 'posts#update'
  put '/posts/:id' => 'posts#update'

  delete '/posts/:id' => 'posts#destroy'
  
  resources :users do
    resources :posts
  end
  
  get '/error_role' => 'errors#error_role'
  get '*path', to: 'errors#error_404', via: :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { minimum: 3 }

end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts , dependent: :destroy

    has_secure_password
    validates :name, presence: true, length: { minimum: 1 }
    validates :login, presence: true, uniqueness: { message: 'already exists'}, length: { minimum: 3 }
    validates :password, length: { in: 3..20 }, :confirmation => true
    validates :role, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ErrorHandling
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
    extend ActiveSupport::Concern

    included do

        rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
        rescue_from ActionController::RoutingError, with: :record_not_found
        

        private

        def record_not_found
            render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
        end
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
    def error_404
        render 'errors/not_found'
    end

    def error_role
        render 'errors/error_role'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.order(updated_at: :desc).page params[:page]
    end

    def create
        if ["redactor", "admin"].include? User.find_by(id:session[:user_id]).role
            @post = Post.create(user_id:session[:user_id], body:post_params[:body], title:post_params[:title])
            redirect_to user_path(session[:user_id])
        else
            redirect_to '/error_role'
        end
    end
    
    def show
        @post = Post.find_by(id:params[:id])
    end

    def edit
        if ["redactor", "admin"].include? User.find_by(id:session[:user_id]).role
            @post = Post.find(params[:id])
            @user = User.find_by(id:session[:user_id])
            
        else
            redirect_to '/error_role'
        end
    end

    def update
        @post = Post.find(params[:id])
    
        if @post.update(post_params)
            redirect_to @post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        if ["redactor", "admin"].include? User.find_by(id:session[:user_id]).role
            @post = Post.find(params[:id])
            @post.destroy
    
            redirect_to root_path
        else
            redirect_to '/error_role'
        end
    end

    private
    def post_params
        params.require(:post).permit(:title, :body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        @user = User.find_by(login:login_params[:login]) 
        return redirect_to '/users/login', alert: "Неправильный логин или пароль" unless @user and @user.authenticate(login_params[:password]) 
        session[:user_id] = @user.id 
        redirect_to @user
    end

    private   
        def login_params
            params.require(:user).permit(:login, :password)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    def index
    end

    def show
        @user = User.find_by(id:params[:id])
        if @user
            @posts = @user.posts.order(updated_at: :desc).page params[:page]
        else
            redirect_to root_path
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(reg_params)
        if @user.save
            session.clear
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
    
        if @user.update(reg_params)
          redirect_to @user
        else
          render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
        user = User.find_by(id:params[:id])
        if user and user.id == session[:user_id]
            user.destroy
    
            redirect_to login_user_path
        end
    end

    def change_role
        if session[:user_id] && (["redactor", "admin"].include? User.find_by(id:session[:user_id]).role)
            @user = User.find_by(id:params[:id])
            if @user
                @user.update_attribute(:role, reg_params[:role])
            end
            redirect_to user_path
        else
            redirect_to '/error_role'
        end
    end

    def list
        @users = User.order(created_at: :asc).page params[:page]
    end

    def clear
        session.delete(:user_id)
        redirect_to login_user_path
    end

    private
        def reg_params
            params.require(:user).permit(:name, :role, :login, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans|Oswald|Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../assets/stylesheets/application.css">
  </head>

  <body style="background: #fff4e8">
    <header class="header_form">
      <div class="header_style">
        <%if User.find_by(id:session[:user_id])%>
          <a style="position: fixed; left: 56%; top:50%; transform: translate(0%, -50%);" href="/users/<%=session[:user_id]%>"> Вы вошли как: <%=User.find_by(id:session[:user_id]).name%><a>
        <%else%>
          <a style="position: fixed; left: 56%; top:50%; transform: translate(0%, -50%);" >Вы вошли как: Гость</a>
        <%end%>
        <a style="position: fixed; left: 31%; top:50%;  transform: translate(-50%, -50%);" href="/">Главная страница</a>
        <a style="position: fixed; left: 39%; top:50%; transform: translate(-50%, -50%);" href="/users/login">Вход</a>
        <a style="position: fixed; left: 48%; top:50%; transform: translate(-50%, -50%);" href="/users/list">Список пользователей<a>
      </div>
    </header>
    

    <div class="rotate-shadows" style="position: fixed; top: 15%; left: 0%;"></div>
    <div class="rotate-shadows" style="position: fixed; top: 15%; left: 100%;"></div>

    <div class="rotate-shadows" style="width: 300px; height: 400px; position: fixed; top: 40%; left: 0%;"></div>
    <div class="rotate-shadows" style="width: 300px; height: 400px; position: fixed; top: 40%; left: 100%;"></div>


    <%= yield %>

  </body>
</html>

app/views/posts/_form_post.html.erb
<%= form_for post do |form| %>
  <p style="margin-bottom:5px">Заголовок</p>
  <textarea name="post[title]" class="text_box", style="margin-top:0px; height:20px"></textarea>

  <p style="margin-bottom:5px; margin-top:0px">Текст</p>
  <textarea name="post[body]" class="text_box", style="margin-top:0px; height:152px"></textarea>

  <%= form.submit value="Утвердить!" %>
<% end %>

app/views/posts/_form_post_create.html.erb
<form accept-charset="UTF-8" action="/users/<%=session[:user_id]%>/posts" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

    <p style="margin-bottom:5px">Заголовок</p>
    <textarea name="post[title]" class="text_box", style="margin-top:0px; height:20px"></textarea>

    <p style="margin-bottom:5px; margin-top:0px">Текст</p>
    <textarea name="post[body]" class="text_box", style="margin-top:0px; height:152px"></textarea>

    <input type="submit" value="Утвердить!">
</form>

app/views/posts/_form_post_edit.html.erb
<%= form_with model: post do |form| %>
  <p style="margin-bottom:5px">Заголовок</p>
  <textarea name="post[title]" class="text_box", style="margin-top:0px; height:20px"><%=post.title%></textarea>

  <p style="margin-bottom:5px; margin-top:0px">Текст</p>
  <textarea name="post[body]" class="text_box", style="margin-top:0px; height:152px"><%=post.body%></textarea>

  <%= form.submit value="Утвердить!" %>
<% end %>

app/views/posts/_form_post_show.html.erb
<div class="text_box">
    <a class="small_text"><%= post.updated_at %><a>
    <a class="small_text" style="margin-left:5px; font-size: 14px;" href="/users/<%= post.user_id %>"><%= User.find_by(id:post.user_id).name %><a><br><br>
    <a class="large_text" style="margin-top:10px; margin-bottom:10px;" href="/posts/<%= post.id %>"><%= post.title %><a><br><br>
    <%= sanitize post.body %>
</div>

app/views/posts/edit.html.erb
<div class="base_form">

<a style="font-size:28px">Редактирование</a>

<%= render "form_post_edit", post: @post%>
<form action=<%=post_path(@post)%> style="margin-top: 20px">
  <button>Выйти из режима редактирования</button>
</form>

</div>

app/views/posts/index.html.erb
<body>
    
    <div class="base_form">
        <a style="font-size:28px">Всего новостных постов: <%= Post.count %></a>

        <ul>
        <% @posts.each do |post| %>
            <li style="margin-bottom:10px">
                <a class="large_text" style="color: rgb(0, 0, 0); font-weight: 500;" href="/posts/<%= post.id %>"><%= post.title %></a>
            </li>
        <% end %>
        </ul>
        <div class = "center"> <%= paginate @posts %> </div>
    </div>
</body>

app/views/posts/show.html.erb
<% if @post%>
    <div class="base_form">
        <% if User.find_by(id:session[:user_id]) %>
            <% if ["admin", "redactor"].include? User.find_by(id:session[:user_id]).role %>
                    <%= link_to "Редактировать профиль", edit_post_path(@post), data: { confirm: "Вы уверены?" }%>
                <div style="margin-top:10px"><%= link_to "Удалить Статью", post_path(@post), method: :delete, data: { confirm: "Вы уверены?" } %></div>
            <% end %>
        <% end %>
        <%= render "form_post_show", post: @post %>
    <%else%>
        <h1 class="base_form">Статья не найдена!</h1>
    <%end%>
</div>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>

  <div style="margin-top: 20px">
    <%= form.label "Имя" %><br>
    <%= form.text_field :name%>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div style="margin-top: 20px">
    <%= form.label "Логин" %><br>
    <%= form.text_field :login %>
    <% user.errors.full_messages_for(:login).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div style="margin-top: 20px">
    <label for="user_password">Пароль</label><br>
    <input id="user_password" name="user[password]" type="password" />
    <% user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div style="margin-top: 20px">
    <label for="user_password_confirmation">Подтверждение пароля</label><br>
    <input id="user_password_confirmation" name="user[password_confirmation]" type="password" />
    <% user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div style="margin-top: 20px">
      <%= form.label "Роль" %><br>
      <div>
      <%= form.radio_button :role, 'reader'%>
      <%= form.label :role, "Читатель", :value => "reader" %>
      </div>
      <div>
      <%= form.radio_button :role, 'redactor'%>
      <%= form.label :role, "Редактор", :value => "redactor" %>
      </div>
      <div>
      <%= form.radio_button :role, 'admin'%>
      <%= form.label :role, "Админ", :value => "admin" %>
      </div>
      <% user.errors.full_messages_for(:role).each do |message| %>
        <div><%= message %></div> 
      <% end %>
  </div>

  <div style="margin-top: 20px">
    <%= form.submit "Утвердить!"%>
  </div>

<% end %>

app/views/users/_form_post.html.erb
<div class="text_box">
    <a class="small_text"><%= post.updated_at %><a>
    <a class="small_text" style="margin-left:5px; font-size: 14px;" href="/users/<%= post.user_id %>"><%= User.find_by(id:post.user_id).name %><a><br><br>
    <a class="large_text" style="margin-top:10px; margin-bottom:10px;"><%= post.title %><a><br><br>
    <%= post.body %>
</div>

app/views/users/edit.html.erb
<div class="base_form">

  <div class="center">
    <a style="font-size:28px">Редактирование</a>

    <%= render "form", user: @user %>

    <form action="/users/<%=@user.id%>" style="margin-top: 20px">
      <button>Выйти из режима редактирования</button>
    </form>
  </div>

</div>

app/views/users/index.html.erb
<body>
    
    <div class="base_form">
        <a style="font-size:28px">Новостные посты: <%= Post.count %></a>

        <ul>
        <% @posts.each do |post| %>
            <li>
                <a class="large_text" style="color: rgb(0, 0, 50);" href="/posts/<%= post.id %>"><%= post.title %></a>
            </li>
        <% end %>
        </ul>

    </div>
</body>

app/views/users/list.html.erb
<body>
    
    <div class="base_form">
        <a style="font-size:28px">Всего пользователей: <%= User.count %></a>

        <ul>
        <% @users.each do |user| %>
            <li>
            <%= link_to user.name, user %>
            </li>
        <% end %>
        </ul>
        <div class = "center"> <%= paginate @users %> </div>

    </div>
</body>

app/views/users/login.html.erb
<div class="base_form">
    <div class="center">
        <form action = '/users/login' method = 'POST'>
            <a style="font-size:28px">Авторизация</a>
            
            <input type = 'hidden' name = 'authenticity_token' value = '<%=form_authenticity_token%>'>
            <div style="margin-top:20px">
                <div>
                    <a>Логин</a><br>
                    <input style="margin-bottom:20px" type = 'login' name = 'user[login]'><br>
                </div>
                <div>
                    <a>Пароль</a><br>
                    <input style="margin-bottom:20px" type = 'password' name = 'user[password]'><br>
                </div>
            </div>
            <input type = 'submit' name = 'submit' value = 'Войти'>
        </form>
        
        <% if flash.alert %>
            <p><%= flash.alert %></p>
        <% end %>
        
        <form action="/users/new" style="margin-top: 20px">
            <button>Перейти к регистрации</button>
        </form>
    <div>
</div>

app/views/users/new.html.erb
<div class="base_form">
  <div class="center">
    <a style="font-size:28px">Регистрация</a>

    <%= render "form", user: @user %>

    <form action="/users/login" style="margin-top: 20px">
      <button>Перейти к авторизации</button>
    </form>
  </div>
</div>

app/views/users/show.html.erb
<body>

<%if @user%>
    <div class="base_form" style="margin-top: 5%">
        <p>Имя пользователя: <%= @user.name %></p>
        <p>Роль: <%= @user.role %></p>
        <%if @user.id == session[:user_id]%>
            <p>Это ваш профиль!</p>
            <br>
            <%= link_to "Редактировать профиль", edit_user_path(@user), data: { confirm: "Вы уверены?" }%>
            <div style="margin-top:10px"><%= link_to "Удалить профиль", user_path(@user), method: :delete, data: { confirm: "Вы уверены?" } %></div>
        <%end%>
        <% if User.find_by(id:session[:user_id]) %>
            <% if User.find_by(id:session[:user_id]).role == "admin" %>
                <br>
                <form accept-charset="UTF-8" action="/users/<%=@user.id%>/change_role" method="post">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

                    <select name="user[role]" id="user_role">
                        <option value="reader">Читатель</option>
                        <option value="redactor">Редактор</option>
                        <option value="admin">Админ</option>
                    </select>

                    <input type="submit" value="Утвердить!">
                </form>
                <a href="/users/clear">Выход</a>
            <% end %>
        <% end %>
    </div>

    <%if @user.id == session[:user_id] and ["admin", "redactor"].include? @user.role %>
        <div class="base_form" style="margin-top: 2%">
            <h2>Создать новый пост:</h2>
            <%= render "posts/form_post_create", user: @user %>
        </div>
    <% end %>

    <div class="base_form" style="margin-top: 2%">
        <%if @user.role == "reader" and @user.posts.length == 0%>
            <h2>Вы не можете писать статьи!</h2>
        <%else%>
            <h2>Опубликованные статьи:</h2>
            <% @posts.each do |post| %>
                <% if post.id != nil %> <%= render "posts/form_post_show", post: post %> <% end %>
            <% end %>
            <div class = "center"> <%= paginate @posts %> </div>
        <%end%>
    </div>
<%else%>
    <h1 class="base_form">Пользователь не найден</h1>
<%end%>

</body>